require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp.luasaga"
require "user.lsp.lspconfig"
require "user.lsp.mason"
require "user.comment"
require "user.nvim-tree"
require "user.lualine"
require "user.telescope"

vim.cmd "colorscheme tokyonight"
